### ISSUE TITLE
Do not allow for all registered users to submit to evaluation queue

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowHook#16]
Currently the docker run command that sets up a project and evaluation queue also sets the ACL of the evaluation queue to be "Public".  It should only be seen by the user setting it up first.

**Comment by brucehoff** [comment]
@thomasyu888 It's just meant to be a demo.  Do you think it's an important tool for people setting up projects and evaluation queues?

**Comment by thomasyu888** [comment]
Hmmm. I think I will add instructions on how to manually link up an evaluation id with a workflow as well.  I guess with the demo, its still unnecessary to share it with the general public.  People can share their evaluation queue as needed to the people that need them.  

I guess I could be biased, because I see way too many challenge queues

**Comment by brucehoff** [comment]
Ok, I made the requested change: https://github.com/Sage-Bionetworks/SynapseWorkflowHook/commit/18cfb3d452bcca98554e89419a912b695ab8d9dc
