### ISSUE TITLE
Add in param to limit number of submissions run at a time

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowHook#19]
Currently, it seems like if there are 10 submission RECEIVED, the hook will run 10 submission at once?

This will be awful for container based challenges.

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/SynapseWorkflowHook/commit/f76fc7fd14b93609906299bd38a7d1b223c05e95
