### ISSUE TITLE
Wrong folder is passed from hook to workflow

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowHook#23]

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/SynapseWorkflowHook/commit/df5a50808a43c1820336f709483868c46d870f60

**Comment by brucehoff** [comment]
@thomasyu888 please update from DockerHub and try again.  You should find that uploaded files now go to the public and private folders for the specific *submission* not just for the specific *submitter*.

**Comment by thomasyu888** [comment]
Fantastic! This works!
