### ISSUE TITLE
What is the retries setting with annotation updates?

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowHook#24]
I set mine at 10 retries and wait time of 3 seconds.  My workflow was failing with the default setting.  I just want to make sure your hook doesn't also fail with the default setting.

**Comment by brucehoff** [comment]
8 attempts with 'exponential back off' in between, starting with 1/2 sec and doubling on each retry, for a total wait time of up to 63 1/2 seconds.
The formula is `a*(b^(n-1)-1)` where `a` is the initial backoff (in this case 1/2 sec), `b` is the backoff multiplier (in this case 2) and `n` is the number of tries (in this case 8).

**Comment by thomasyu888** [comment]
I like it.  Thanks for the explanation!
