### ISSUE TITLE
Wrong folder shared with submitters

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowHook#25]
Submitters will be getting a link to the `..._LOCK` folder (or any subfolder of the _LOCK folder controlled by the same ACL) even when `SHARE_RESULTS....` is false.

I can confirm that the submitter only has "Can View" permissions.  Can we switch the folder that is sent back to always be the not `..._LOCK` folder

**Comment by brucehoff** [comment]
The change I made is to say nothing about the shared folder in the case that SHARE_RESULTS is set to false.  If a specific workflow is sending a certain output to the user it can send its own notification and/or display in the submission dashboard.

https://github.com/Sage-Bionetworks/SynapseWorkflowHook/commit/d80793f10ab99e59a8458841fd4c20fe1b5216f8

**Comment by thomasyu888** [comment]
Can confirm that the folder isn't linked anymore.  However, the subject title is "Workflow Logs Available".  Perhaps this should be something different like "Submission Processing"

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/SynapseWorkflowHook/commit/538af5fcd20c6a52a57a1c62fd4bcdf390ef0b0b
