### ISSUE TITLE
EVALUATION_IN_PROGRESS vs MAX_CONCURRENT_WORKFLOWS

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowHook#27]
The Hook sets the statuses of more than 4 submissions even though the MAX_CONCURRENT_WORKFLOWS is set at 4.  Is this expected? It seems to be running more than 4 workflows at once even with this variable set.

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/SynapseWorkflowHook/commit/e72beeade9b9233d530b3e3edf6fa37c4738d08a

**Comment by brucehoff** [comment]
@thomasyu888 , once this finishes building:
https://hub.docker.com/r/sagebionetworks/synapseworkflowhook/builds/
You can `docker pull sagebionetworks/synapseworkflowhook` and you will have the fix for this issue.
