### ISSUE TITLE
Confusing submission instructions for evaluation queue

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowHook#4]
Am I submitting a prediction file / docker image + sha digest, or am I submitting a .cwl parameter file.

Instructions in submitting to the queue say:

"Submission InstructionsYour workflow submission should be a .cwl parameters file."

**Comment by brucehoff** [comment]
https://github.com/Sage-Bionetworks/SynapseWorkflowHook/commit/d2a0636f3ef5ea8443713162194430ea069e85fd
