### ISSUE TITLE
Could the workflow hook give the cwl workflow additional parameters?

### ISSUE THREAD

**Issue by andrewelamb** [Sage-Bionetworks/SynapseWorkflowHook#41]
Currently the workflow has to take these parameters:

submissionId: ID of the Synapse submission to process
adminUploadSynId: ID of a folder accessible only to the submission queue administrator
submitterUploadSynId: ID of a folder accessible to the submitter
workflowSynapseId:  ID of the Synapse entity containing a reference to the workflow file(s)
synapseConfig: ~/.synapseConfig file that has your Synapse credentials

How feasible would it to give the workflow other parameters? Such as the id of the evaluation queue it's pulling submission ids from. This would be fairly useful for a certain type of challenge we're running.

**Comment by thomasyu888** [comment]
The workaround is that in the process of downloading the submission, we link the evaluation id as an output of the `download_submission.cwl` tool.

**Comment by brucehoff** [comment]
As @thomasyu888 says, the submission object (metadata) includes the evaluation ID.  When you get the submission object (even if you don't download the associated submitted file) you get this info.  If that's *not* sufficient, please reopen this issue.
