### ISSUE TITLE
[ERROR] Only the creator of a FileHandle can assign it to an Entity

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/SynapseWorkflowHook#43]
Context:

- We have two Synapse users: `phil` and `admin`.
- `phil` has submitted a Synapse entity `entity` to an evaluation queue `eval`.
- `admin` has been given Download permissions on `entity`.
- `admin` has been given Administrator permissions on `eval` (the key of `EVALUATION_TEMPLATES` in `.env`), `workflow` (the value of `EVALUATION_TEMPLATES`), and `workflow_output` (`WORKFLOW_OUTPUT_ROOT_ENTITY_ID`).
- `phil` is the original creator of these entities and also has Administrator permissions on `eval`, `workflow`, and `workflow_output`.
- If we run `workflow` locally with `cwl-runner` using `admin`'s credentials in the passed `.synapseConfig`, the workflow executes successfully.
- If we run the workflow hook using `phil`'s Synapse credentials, the workflow hook processes the submission successfully.
- If we re-submit `entity` to `eval` and replace `phil`'s credentials with `admin`'s credentials, an error is thrown and the workflow hook exits. 

Full logs attached: [workflow-hook-logs.txt](https://github.com/Sage-Bionetworks/SynapseWorkflowHook/files/2912214/workflow-hook-logs.txt)

**Comment by brucehoff** [comment]
> Full logs attached: workflow-hook-logs.txt

I see the error is:

```
Only the creator of a FileHandle can assign it to an Entity.  FileHandleId = '37114365', UserId = '3380061'"
```

That's by design, it's not a bug.  If you can say more about what is the aim of the workflow, we can advise how to use Synapse to accomplish it.

**Comment by philerooski** [comment]
> That's by design

I understand where you're coming from. But the way I see it, I'm using the workflow hook properly (and I can demonstrate it, by a successful execution using one credential pair), but when I run the exact same workflow, exact same input, using different credentials -- but with the same permissions granted to those credentials as the first on all relevant files -- the workflow hook breaks.

My question for you is why this would affect the functionality of the workflow hook? The logs seem to suggest that the error occurred during the hook execution, rather than in the execution of the provided workflow.

**Comment by brucehoff** [comment]
Note:  @philerooski and I discussed in person.  He mentioned that the same code worked in a past (non-workflow-based) application.  That's hard to reconcile with my knowledge of the permissions around file handles.  Phil offered to investigate further and share what he learns.

**Comment by philerooski** [comment]
This workflow does execute successfully locally, actually. Here's the call I'm making:
```
cwl-runner scoring_harness_workflow.cwl --submissionId 9685453 --adminUploadSynId syn123123 --submitterUploadSynId syn123123 --workflowSynapseId syn12312 --synapseConfig .synapseConfig
```
This does not throw any errors, and I am using `admin`'s credentials.

But running the workflow using the hook with `admin`'s credentials I get the above error log.

Again, If I run the workflow as `phil`, then the hook executes successfully. But changing the credentials to `admin`, and keeping everything else the same, I run into the above error.

**Here is something new:** If I delete every submission from the evaluation queue, the hook still breaks using `admin`'s credentials. If I use `phil`'s credentials, the hook will wait for a job as expected. This seems to suggest that the hook is breaking before it ever runs my workflow.

**Comment by philerooski** [comment]
If I upload the workflow zip file and create the log root directory using the same account which is invoking the workflow hook (i.e., has credentials set in .env), the workflow successfully waits for new jobs.

So the root of the issue is that I was creating the workflow and log directory on Synapse as `phil`, but running the hook as `admin`. This is despite the fact that `admin` was granted the same permissions as `phil` on these entities, but still unsurprising given that the hook broke trying to do something with the file handle of one of these entities

**Comment by philerooski** [comment]
I filed a Jira (PLFM-5423) and found that the file handle referenced in the raised exception in the log file above was the zipped workflow.

**Comment by brucehoff** [comment]
Not sure why you would be making a new file entity from the file handle underlying the zipped workflow.  Are you thinking that this is something the workflow hook is doing?

**Comment by philerooski** [comment]
It's not something I'm doing, but it does seem like the hook is doing something with the file handle. Maybe it has something to do with how externally linked files are accessed on Synapse? The file handle might be indirectly accessed, or created on demand.

I honestly have no idea how these things work in the back end.

**Comment by brucehoff** [comment]
Indeed there is an error in the workflow hook.  It is in WorkflowHook.getWorkflowURLAndEntrypoint() which mistakenly calls Synapse.getRawFileHandle()

**Comment by brucehoff** [comment]
Fixed!  https://github.com/Sage-Bionetworks/SynapseWorkflowHook/commit/4c14c3b8c49eff46c3caef812bac233fccb00487

Please try when this build is done:
https://cloud.docker.com/u/sagebionetworks/repository/registry-1.docker.io/sagebionetworks/synapseworkflowhook/builds/4517bd0d-83a0-4a18-bbc3-53f778ad11e1
