### ISSUE TITLE
Create stable versions of the hook.

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowHook#47]
The workflow hook is being used for active challenges.  We should pull down specific tags if continuous development is going to occur to make sure that bugs aren't introduced to active challenges

We should release a version after #45  and #46, and specify the stable tag in `docker-compose.yaml`

```
sagebionetworks/synapseworkflowhook:v1.0
```

**Comment by brucehoff** [comment]
That's a good idea.  It's also an opportunity to change the name of the github repo and docker container to 'Synapse Workflow Orchestrator' as suggested by @jaeddy .

**Comment by thomasyu888** [comment]
This will be done: https://github.com/Sage-Bionetworks/SynapseWorkflowOrchestrator/tree/release-1.0
