### ISSUE TITLE
Had to generate my own docker cert

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowHook#5]
https://docs.docker.com/engine/security/https/#other-modes

**Comment by brucehoff** [comment]
Need to give guidance as to how to connect to the Docker engine on a variety of platforms.  The immediate need is to connect on MacOS.

**Comment by thomasyu888** [comment]
Should add information that you get these files by installing docker-machine.  Unsure of how to create a docker env just for your Mac but you can create docker envs with docker-machine and it will create certs and the docker_engine_link

**Comment by brucehoff** [comment]
Certs are not involved when connecting to the Docker daemon/engine via the non-networked `unix://` socket.  Updated the logic so as not to require certs in this case, and verified it works.  So now you need not generate certs!

https://github.com/Sage-Bionetworks/SynapseWorkflowHook/commit/f08a35c0d718d3071c7314ca0b20a346d4c576fd
