### ISSUE TITLE
Running docker workflow

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/SynapseWorkflowHook#7]
Can the workflow hook look for parameters such as:

ENTRY_POINT
INPUT
OUTPUT
DOCKER_CONFIG

Or do these need to be hardcoded?

**Comment by brucehoff** [comment]
@thomasyu888  Can you give more context as to what these parameters are for?  E.g., `ENTRY_POINT` sounds like a Docker parameter.  What container would this be applied to?

**Comment by thomasyu888** [comment]
After discussion, I realized I would hardcode a lot of these in the workflow.  The only issue is going to be passing in docker credentials.  I feel like we should also allow a docker config file along with the synapseConfig to be passed in.

**Comment by thomasyu888** [comment]
https://github.com/Sage-Bionetworks/ChallengeWorkflowTemplates/blob/master/get_docker_config.cwl
